#!/bin/bash
set -e

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS OBETA_STAGING;
    CREATE DATABASE IF NOT EXISTS OBETA_PRODUCTION;

    CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
    CREATE USER IF NOT EXISTS 'mpmd'@'%' IDENTIFIED BY '';

    GRANT ALL PRIVILEGES ON OBETA_STAGING.* TO '${MYSQL_USER}'@'%';
    GRANT ALL PRIVILEGES ON OBETA_PRODUCTION.* TO '${MYSQL_USER}'@'%';

    GRANT ALL PRIVILEGES ON OBETA_STAGING.* TO 'mpmd'@'%';
    GRANT ALL PRIVILEGES ON OBETA_PRODUCTION.* TO 'mpmd'@'%';

    CREATE TABLE IF NOT EXISTS OBETA_STAGING.test (
        id INT NOT NULL AUTO_INCREMENT,
        PRIMARY KEY (id)
    );

    CREATE TABLE IF NOT EXISTS OBETA_PRODUCTION.test (
        id INT NOT NULL AUTO_INCREMENT,
        PRIMARY KEY (id)
    );

    FLUSH PRIVILEGES;
EOSQL