#!/bin/bash
set -e

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS OBETA_STAGING;
    CREATE DATABASE IF NOT EXISTS OBETA_PRODUCTION;

    CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
    CREATE USER IF NOT EXISTS 'mpmd'@'%' IDENTIFIED WITH mysql_native_password BY '';

    GRANT ALL PRIVILEGES ON OBETA_STAGING.* TO '${MYSQL_USER}'@'%';
    GRANT ALL PRIVILEGES ON OBETA_PRODUCTION.* TO '${MYSQL_USER}'@'%';

    GRANT ALL PRIVILEGES ON OBETA_STAGING.* TO 'mpmd'@'%';
    GRANT ALL PRIVILEGES ON OBETA_PRODUCTION.* TO 'mpmd'@'%';

    FLUSH PRIVILEGES;
EOSQL